import Head from "next/head";
import styles from "@/styles/Home.module.css";
import customStyle from "@/styles/Custom.module.css";
import mypic from "../../asset/banner_image.png";
import Image from "next/image";
import BlogList from "../components/BlogList";
import { useRouter } from "next/router";
// import { Router } from "next/router";
export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>BLOG EXPERTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, Blog experts" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="bg-dark text-white col-sm-12 row ml-5 mr-5">
          <div className="col-sm-6 d-flex justify-content-center mt-5 ">
            <div className={customStyle.banner}>
              <p className="display-2 mt-5 fw-bolder">We Love to Share!</p>
              <p className="display-2 fw-bolder">Stay Informed & Inspired.</p>
              <p className="h5 mt-5 fw-lighter">
                {" "}
                Discover innovative stories and handpicked key insights from
                fellow engineering managers and tech leaders to level up your
                skills. From full stack development to DevOps and coding
                strategies, we cover it all.xx
              </p>
              <button onClick={()=>{router.push('/create-blog-page')}}className="btn btn-success  mt-5">Post Your Blog</button>
            </div>
          </div>
          <div className="col-sm-6 ">
            <div className="d-flex justify-content-center ">
              <Image
                className="p-5"
                src={mypic}
                width={623}
                height={588}
                alt="blog experts"
              />
            </div>
          </div>
        </div>

        <BlogList />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
